### ISSUE TITLE
Robot Pictures Page

### ISSUE THREAD

**Issue by Glorken** [FRC-Team-5957/Website#10]
In the gallery, the page with pictures of the robot has two issues that I noticed.

Firstly, @mbqwertyaaa didn't you say that the pictures shouldn't be hosted on the github? I'm not against either way, but all I noticed was that the banners, the team icons, and the robot picture were the only pictures kept here.

Secondly, the statement that we used the kit AM14U3 is partially false. We used the standard 2016 FRC Kit of Parts, along with some other components that were purchased later. Technically, we did use the chassis kit because it was in the KoP, but it is nowhere near everything used.

**Comment by mbqwertyaaa** [comment]
These have been fixed, thanks.
