### ISSUE TITLE
Mobile Compatibility

### ISSUE THREAD

**Issue by Glorken** [FRC-Team-5957/Website#2]
There is some difficulty navigating on mobile. This is not high priority, but definitely an issue of a kind.

Some I found:
- [ ] Demo Navbar always obscures the top of the screen
- [ ] Unable to navigate submenus on the navbar
- [ ] Images in galleries take up the entire width of the screen, causing the bullets to appear above them.

**Comment by mbqwertyaaa** [comment]
Did I ever mention that the part of the website in the legacy/ folder is legacy, and therefore deprecated? It is just the stand in. The navbar staying at the top of the screen in mobile is supposed to happen. The gallery images will have proper changes to them when I get there. As far as I'm concerned, only 3 pages exist. The home (index.html), the demo (base.html), and the forum (forum.html).

**Comment by Glorken** [comment]
I understand about the legacy; however, the issues I had were not in the legacy section. I used rawgit to only view the demo and home.
