### ISSUE TITLE
Members Page

### ISSUE THREAD

**Issue by mbqwertyaaa** [FRC-Team-5957/Website#9]
Discuss what the members page should look like.

**Comment by wayejalen** [comment]
How about having a list of the groups (Programming, Engineering, etc.), then put the members of each group under the corresponding group name.

example
# Programming
   (Lead)
   Member
   Member 
# Engineering
   (Lead)
   Member
   Member

**Comment by mbqwertyaaa** [comment]
What I was thinking of was having tabs like the side switching tabs in the top left.

**Comment by wayejalen** [comment]
That could work also.

**Comment by mbqwertyaaa** [comment]
Finished
